// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  /** 运行环境 */
  ENVIRONMENT: 'production' | 'development'
  /** EPG 列表地址 */
  EPG_URLS: string[]
  /** M3U 列表地址 */
  M3U_URLS: string[]
}
