// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  /** 运行环境 */
  ENVIRONMENT: 'production' | 'development'
  /** 上游 M3U 地址 */
  M3U_URLS: string[]
  /** 上游 EPG 地址 */
  EPG_URL: string
}
